owncloud:
  image: owncloud
  ports:
    - ${client_port}:80
  links:
    - db
  volumes:
    - owncloud_files:/var/www/html
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=${db_password}
  volumes:
    - owncloud_db:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

code:
  image: collabora/code
  environment:
    - domain=${escaped_domain}
    - username=${username_office}
    - password=${password_office}
  cap_add:
    - MKNOD
