.catalog:
  name: "Owncloud"
  version: "v0.1-educaas"
  description: "Library service powered by Owncloud"
  uuid: owncloud-0
  minimum_rancher_version: v0.51.0
  questions:
  questions:
    - variable: client_port
      description: "Port to access Owncloud"
      label: "Client Port"
      required: true
      default: "80"
      type: "int"
    - variable: db_password
      description: "Password for database"
      label: "Password (default: password)"
      required: true
      default: "password"
      type: "password"
