.catalog:
  name: "Owncloud"
  version: "v0.1-educaas"
  description: "Library service powered by Owncloud"
  uuid: odoo-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: client_port
      description: "Port to access Owncloud"
      label: "Client Port"
      required: true
      default: "8070"
      type: "int"
