gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: ${gitlab_hostname}
  environment:
    # GITLAB_OMNIBUS_CONFIG: |
      # external_url 'URL'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - ${http_port}:80
    - ${https_port}:443
    - ${ssh_port}:22
  # volumes:
    # - '/srv/gitlab/config:/etc/gitlab'
    # - '/srv/gitlab/logs:/var/log/gitlab'
    # - '/srv/gitlab/data:/var/opt/gitlab'
