gitlab-server:
  ports:
  - ${ssh_port}:22
  - ${http_port}:80
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volumes_from:
  - gitlab-data

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:latest
  volumes:
  - /etc/gitlab
  - /var/log/gitlab
  - /var/opt/gitlab
