.catalog:
  name: Gitlab Community
  version: 0.1
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "David A. Lareo <dalareo@gmail.com>"
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname"
      label: "Hostname or IP:"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: "http_port"
      description: "Public non-secure port"
      label: "HTTP port"
      required: true
      default: "80"
      type: "int"
    - variable: "https_port"
      description: "Public secure port"
      label: "HTTPS port"
      required: true
      default: "443"
      type: "int"
    - variable: "ssh_port"
      description: "SSH connections port"
      label: "SSH port"
      required: true
      default: "22"
      type: "int"
