db:
  image: mongo
  volumes:
    - wekan_data:/data/db
    - wekan_dump:/dump
  command: mongod --smallfiles --oplogSize 128

app:
  image: mquandalle/wekan
  links:
    - db
  environment:
    - MONGO_URL=mongodb://wekandb/wekan
    - ROOT_URL=http://localhost:${client_port}
  ports:
    - ${client_port}:80
