mongo:
  tty: true
  image: mongo
  stdin_open: true
  volumes:
     - rc_db:/data/db
     - rc_db_dump:/dump
     - rc_db_config:/data/configdb

  command: mongod --smallfiles --oplogSize 128
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

rocketchat:
  tty: true
  image: rocket.chat
  stdin_open: true
  volumes:
    - rc_uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://${hostname}:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
#hubot:
#  tty: true
#  image: rocketchat/hubot-rocketchat
#  stdin_open: true
#  environment:
#    - ROCKETCHAT_URL=rocketchat:3000
#    - ROCKETCHAT_ROOM=GENERAL
#    - ROCKETCHAT_USER=bot
#    - ROCKETCHAT_PASSWORD=botpassword
#    - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
#    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
#  links:
#    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
#  ports:
#    - 3001:8080
#  labels:
#    io.rancher.scheduler.affinity:host_label: availability=permanent
