lb:
  ports:
  - 80:80
  image: rancher/load-balancer-service
  links:
  - rocketchat:rocketchat
  labels:
    # Put load balancer containers only on hosts without label availability=temporal
    io.rancher.scheduler.affinity:host_label_ne: availability=temporal
    # Requests to http://app.example.com/foo:80 should be routed to web1 over port 8000
    io.rancher.loadbalancer.target.etherpad: rocketchat.educaas.io:80=3000
mongo:
  image: mongo
  volumes:
     - rc_db:/data/db
     - rc_db_dump:/dump
  command: mongod --smallfiles --oplogSize 128
  labels:
    # Put load balancer containers only on hosts without label availability=temporal
    io.rancher.scheduler.affinity:host_label_ne: availability=temporal

rocketchat:
  image: rocketchat/rocket.chat:latest
  volumes:
     - rc_uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://yourhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  labels:
    # Put load balancer containers only on hosts without label availability=temporal
    io.rancher.scheduler.affinity:host_label_ne: availability=temporal

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=botpassword
    - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
  labels:
    # Put load balancer containers only on hosts without label availability=temporal
    io.rancher.scheduler.affinity:host_label_ne: availability=temporal
