  simplesamlphp:
    image: dalareo/simplesamlphp
    tty: true
    stdin_open: true
    volumes:
      - saml_config:/var/simplesamlphp/config
    ports:
      - "${saml_port}:80"
    labels:
      io.rancher.scheduler.affinity:host_label: availability=permanent
