discourse:
    image: bitnami/discourse:latest
    volumes:
      - discourse_data:/bitnami
    links:
      - postgresql
      - redis
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=${db_password}
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=${db_password}
      - SMTP_HOST=${smtp_server}
      - SMTP_PORT=${smtp_port}
      - SMTP_USER=${smtp_username}
      - SMTP_PASSWORD=${smtp_password}
      - SMTP_TLS=true
    ports:
     - ${client_port}:3000
    labels:
       # Make db only run on hosts that do not have a availability=temporal label
       io.rancher.scheduler.affinity:host_label: availability=permanent
postgresql:
    image: bitnami/postgresql:latest
    volumes:
      - discourse_db:/bitnami
    labels:
       # Make db only run on hosts that do not have a availability=temporal label
       io.rancher.scheduler.affinity:host_label: availability=permanent

redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
       # Make db only run on hosts that do not have a availability=temporal label
       io.rancher.scheduler.affinity:host_label: availability=permanent
