app:
  tty: true
  image: campbellsoftwaresolutions/osticket
  stdin_open: true
  links:
    - database:mysql
  environment:
    SMTP_HOST: ${smtp_host} 
    SMTP_PORT: ${smtp_port}
    SMTP_FROM: ${smtp_from}
    SMTP_USER: ${smtp_user}
    SMTP_PASSWORD: ${smtp_password}
  volumes:
    - osticket_files:/data
  labels:
    # Make db only run on hosts that do not have a availability=temporal label
    io.rancher.scheduler.affinity:host_label: availability=permanent
database:
  tty: true
  image: mysql
  stdin_open: true
  environment:
    MYSQL_ROOT_PASSWORD: ${db_password}
    MYSQL_USER: osticket
    MYSQL_PASSWORD: $[db_password}
    MYSQL_DATABASE: osticket
  volumes:
    - osticket_db:/var/lib/mysql
  labels:
    # Make db only run on hosts that do not have a availability=temporal label
    io.rancher.scheduler.affinity:host_label: availability=permanent 
