.catalog:
  name: "Known"
  version: "v0.1-educaas"
  description: "Social publishing platform. Your personal API"
  uuid: ghost-0
  minimum_rancher_version: v0.51.0
  questions:
  - variable: client_port
    description: "Port to access Known"
    label: "Client Port"
    required: true
    default: "8000"
    type: "int"
  - variable: db_password
    description: "Password for database"
    label: "Password (default: known)"
    required: true
    default: "known"
    type: "password"
  - variable: root_password
    description: "Password for database"
    label: "Root Password (default: known)"
    required: true
    default: "known"
    type: "password"
  - variable: db_user
    description: "User for database"
    label: "User (default: known)"
    required: true
    default: "known"
    type: "string"
  - variable: db_name
    description: "Name for database"
    label: "DB Name (default: known)"
    required: true
    default: "known"
    type: "string"
