ethercalc:
  tty: true
  image: audreyt/ethercalc
  stdin_open: true
  ports:
    - ${client_port}:8000
  links:
    - redis:redis
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

redis:
  tty: true
  image: redis:latest
  stdin_open: true
  volumes:
    - ethercalc_db:/data
  command: redis-server --appendonly yes
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent
