loomio:
    image: loomio/loomio:stable
    volumes:
        - loomio_uploads:/loomio/public/system
        - loomio_files:/loomio/public/files
    links:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:${db_password}@db/lo
    ports:
     - ${client_port}:3000
    labels:
       # Make db only run on hosts that do not have a availability=temporal label
       io.rancher.scheduler.affinity:host_label: availability=permanent
db:
    image: postgres:9.6
    volumes:
     - loomio_db:/pgdata
    environment:
     - POSTGRES_PASSWORD=${db_password}
     - PGDATA=/pgdata
    labels:
       # Make db only run on hosts that do not have a availability=temporal label
       io.rancher.scheduler.affinity:host_label: availability=permanent
