.catalog:
  name: "Loomio"
  version: v0.1-educaas
  description: "Tomemos las decisiones entre todos."
  uuid: loomio-0
  questions:
    - variable: client_port
      description: "Port to access loomio"
      label: "Client Port"
      required: true
      default: "10088"
      type: "int"
    - variable: db_password
      description: "DB password"
      label: "DB password"
      required: true
      default: "password"
      type: "password"
    - variable: smtp_user
      description: "SMTP user and support email"
      label: "SMTP user"
      required: true
      default: "user@example.com"
      type: "string"
    - variable: smtp_password
      description: "SMTP password"
      label: "SMTP password"
      required: true
      default: "password"
      type: "password"
    - variable: smtp_port
      description: "Port to access SMTP"
      label: "SMTP Port"
      required: true
      default: "587"
      type: "int"
    - variable: domain
      description: "Loomio installation domain"
      label: "Domain"
      required: true
      default: "example.com"
      type: "string"
    - variable: smtp_server
      description: "SMTP server address"
      label: "SMTP server"
      required: true
      default: "smtp.example.com"
      type: "string"
