db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: ${root_pswd}
#  volume_driver: convoy-nfs
  volumes:
    - etherpad_db:/var/lib/mysql
  labels:
    # Make db only run on hosts that do not have a availability=temporal label
    io.rancher.scheduler.affinity:host_label_ne: availability=temporal

etherpad:
  image: tvelocity/etherpad-lite
  ports:
    - ${client_port}:9001
  links:
    - db:mysql
  environment:
    ETHERPAD_TITLE: ${title}
    ETHERPAD_ADMIN_PASSWORD: ${admin_pswd}
    ETHERPAD_SESSION_KEY: ${session_key}
  labels:
    # Make db only run on hosts that do not have a availability=temporal label
    io.rancher.scheduler.affinity:host_label_ne: availability=temporal
