etherpad:
   tty: true
   image: tvelocity/etherpad-lite
   stdin_open: true
   ports:
     - ${client_port}:9001
   links:
     - db_data:mysql
   volumes_from:
     - db_data
   environment:
     ETHERPAD_TITLE: ${title}
     ETHERPAD_ADMIN_PASSWORD: ${admin_pswd}
     ETHERPAD_SESSION_KEY: ${session_key}
   labels:
     io.rancher.scheduler.affinity:host_label: availability=permanent
     io.rancher.sidekicks: db_data

db_data:
   tty: true
   image: mysql
   stdin_open: true
   volumes:
      - etherpad_db:/var/lib/mysql
      - etherpad_settings:/opt/etherpad_lite/var
   environment:
     MYSQL_ROOT_PASSWORD: ${root_pswd}

