etherpad_db:
  tty: true
  image: mariadb
  stdin_open: true
  environment:
    MYSQL_ROOT_PASSWORD: ${root_pswd}
  volumes:
    - eth_db:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

etherpad:
  tty: true
  image: tvelocity/etherpad-lite
  stdin_open: true
  ports:
    - ${client_port}:9001
  links:
    - etherpad_db:mysql
  volumes:
    - eth_conf:/opt/etherpad-lite/var
  environment:
    ETHERPAD_TITLE: ${title}
    ETHERPAD_ADMIN_PASSWORD: ${admin_pswd}
    ETHERPAD_SESSION_KEY: ${session_key}
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent
