
etherpad_db:
  tty: true
  image: mariadb
  stdin_open: true
  environment:
    MYSQL_ROOT_PASSWORD: ${root_pswd}
  volumes_from:
    - etherpad_data

etherpad_data:
  tty: true
  image: ubuntu
  stdin_open: true
  net: none
  volume_driver: convoy-nfs
  volumes:
    - etherpad_db:/var/lib/mysql
    - etherpad_settings:/opt/etherpad-lite/var

etherpad:
  tty: true
  image: tvelocity/etherpad-lite
  stdin_open: true
  ports:
    - ${client_port}:9001
  links:
    - etherpad_db:mysql
  volumes_from:
    - etherpad_data
  environment:
    ETHERPAD_TITLE: ${title}
    ETHERPAD_ADMIN_PASSWORD: ${admin_pswd}
    ETHERPAD_SESSION_KEY: ${session_key}
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent
    io.rancher.sidekicks: etherpad_data, etherpad_db
