.catalog:
  name: "Etherpad"
  version: v0.1-educaas
  description: "Online editor providing collaborative editing in real-time"
  minimum_rancher_version: v1.0.0-rc2
  questions:
    - variable: client_port
      description: "Port to access Etherpad"
      label: "Client Port"
      required: true
      default: "9001"
      type: "int"
    - variable: title
      description: "Etherpad site title"
      label: "Site Title"
      required: true
      default: "Etherpad"
      type: "string"
    - variable: session_key
      description: "Etherpad session key to import another site"
      label: "Session key"
      required: true
      default: "thisisthesessionkey"
      type: "string"
    - variable: admin_pswd
      description: "Password to access to /admin section"
      label: "Admin password"
      required: true
      default: "changeme1"
      type: "string"
    - variable: root_pswd
      description: "Root password to access DB"
      label: "Root password"
      required: true
      default: "changeme1"
      type: "string"
