postgres:
    image: postgres

taigaback:
    image: ipedrazas/taiga-back
    links:
        - postgres:postgres
    ports:
        - "${backend_port}:8000"

taigafront:
    image: ipedrazas/taiga-front
    links:
        - taigaback:taiga-back
    ports:
        - "${frontend_port}:80"
    environment:
        - "API_NAME=${domain}"
