gogs:
    image: gogs/gogs:latest
    links:
        - mysql:db
    volumes:
        - gogs_data:/data

mysql:
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=${mysql_password}
        - MYSQL_DATABASE=gogs
    volumes:
        - gogs_db:/var/lib/mysql
