.catalog:
  name: "Gogs"
  version: "v0.8.43"
  description: "Un servidor Git en tu propia infraestructura fácil de gestionar, como Github."
  uuid: gogs-0
  minimum_rancher_version: v1.2
  questions:
    - variable: http_port
      description: "http port to access gogs webui"
      label: "Http Port"
      required: true
      default: "10080"
      type: "int"
    - variable: mysql_password
      description: "mysql root password"
      label: "Mysql Password"
      required: true
      default: "password"
      type: "string"
