.catalog:
  name: "Gogs"
  version: "v0.8.43"
  description: "A painless self-hosted Git service"
  uuid: gogs-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: http_port
      description: "http port to access gogs webui"
      label: "Http Port"
      required: true
      default: "10080"
      type: "int"
    - variable: mysql_password
      description: "mysql root password"
      label: "Mysql Password"
      required: true
      default: "password"
      type: "string"

gogs:
