seafile:
  image: dalareo/seafile
  ports:
#    - 10001:10001
#    - 12001:12001
    - ${client_port}:8000
#    - 8080:8080
    - ${file_port}:8082
  volumes_from:
    - data
  environment:
    AUTOSTART: 'true'
  labels:
    io.rancher.sidekicks: data
    io.rancher.scheduler.affinity:host_label: availability=permanent

data:
  image: dalareo/seafile-data
  net: none
  volumes:
    - seafile_data:/opt/seafile

