seafile:
  tty: true
  image: dalareo/seafile
  stdin_open: true
  ports:
#    - 10001:10001
#    - 12001:12001
    - ${client_port}:8000
#    - 8080:8080
    - ${file_port}:8082
  links:
    - data
  volumes_from:
    - data
  environment:
    AUTOSTART: 'true'
  labels:
    io.rancher.scheduler.affinity:host_label_ne: availability=temporal, nfs=true 
    io.rancher.sidekicks: data

data:
  tty: true
  command:
    - cat
  image: dalareo/seafile-data
  stdin_open: true
  net: none
  volumes:
    - seafile_data:/opt/seafile
