seafile:
  tty: true
  image: dalareo/seafile
  stdin_open: true
  ports:
#    - 10001:10001
#    - 12001:12001
    - ${client_port}:8000
#    - 8080:8080
    - ${file_port}:8082
  volumes:
    - seafile_data:/opt/seafile
  command: bash -c "/opt/seafile/seafile-server-latest/seafile.sh start && /opt/seafile/seafile-server-latest/seahub.sh start"
  environment:
    AUTOSTART: 'true'
  labels:
#    io.rancher.sidekicks: data
    io.rancher.scheduler.affinity:host_label: availability=permanent

#data:
#  tty: true
#  image: dalareo/seafile-data
#  command: /bin/true
#  stdin_open: true
#  net: none
#  volumes:
#    - seafile_data:/opt/seafile
#  labels:
#    io.rancher.scheduler.affinity:host_label: availability=permanent
