version: '2'
services:
  seafile:
     image: dalareo/seafile
     ports:
      - ${public_port}:8000
      - ${file_port}:8082
     volumes:
      - seafile_data:/opt/seafile
     links:
      - mysql:db
     entrypoint: tail -f /dev/null
     labels:
        io.rancher.scheduler.affinity:host_label: availability=permanent

  mysql:
     image: mysql:5.7
     ports:
      - 3306
     volumes:
      - seafile_db:/var/lib/mysql
     environment:
      - MYSQL_DATABASE=seafile
      - MYSQL_USER=seafile
      - MYSQL_PASSWORD=${password}
      - MYSQL_ROOT_PASSWORD=${password}
     labels:
        io.rancher.scheduler.affinity:host_label: availability=permanent
