.catalog:
  name: "Seafile"
  version: "v0.1-educaas"
  description: "Sincroniza tus archivos entre dispositivos y comparte con tu equipo, como Dropbox."
  uuid: seafile-0
  questions:
    - variable: public_port
      description: "Port to access Seafile"
      label: "Client Port"
      required: true
      default: "8000"
      type: "int"
    - variable: file_port
      description: "Port to access Seafile files"
      label: "Files Port"
      required: true
      default: "8082"
      type: "int"
    - variable: password
      description: "MySql DB password"
      label: "Database password"
      default: "password"
      type: "string"
