.catalog:
  name: "Seafile"
  version: "v0.1-educaas"
  description: "Reliable and High Speed File Sync and Share"
  uuid: seafile-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: client_port
      description: "Port to access Seafile"
      label: "Client Port"
      required: true
      default: "8000"
      type: "int"
    - variable: file_port
      description: "Port to access Seafile files"
      label: "Files Port"
      required: true
      default: "8082"
      type: "int"
