convoy-gluster:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label_soft: ${HOST_LABEL}
  privileged: true
  pid: host
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /var/run:/host/var/run
    - /etc/docker/plugins:/etc/docker/plugins
  external_links:
    - "${GLUSTERFS_SERVICE}:glusterfs"
  image: rancher/convoy-agent:v0.1.2
  command: volume-agent-glusterfs

convoy-gluster-storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.affinity:host_label_soft: ${HOST_LABEL}
  image: rancher/convoy-agent:v0.1.2
  command: storagepool-agent
