.catalog:
    name: "Convoy GlusterFS"
    version: "v0.1"
    description: "Convoy GlusterFS - Docker volume plugin"
    questions:
     - variable: "VOLUME_POOL"
       description: "Name of the GlusterFS Volume"
       label: "GlusterFS Volume"
       required: true
       type: "string"
       default: my_vol
     - variable: "HOST_LABEL"
       label: "Host label"
       description: "Specify a Rancher host label here that will be used to determine where the Convoy GlusterFS service is deploy. This will determine what hosts can access the volumes managed by this stack."
       type: "string"
       default: convoy.glusterfs=true
       required: true
     - variable: "GLUSTERFS_SERVICE"
       label: "GlusterFS Service"
       type: "service"
       required: true
       description: Service that is running GlusterFS

convoy-gluster:
    metadata:
        volume_pool: "${VOLUME_POOL}"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

convoy-gluster-storagepool:
    scale: 1
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
