odoo:
  image: odoo:10.0
  ports:
    - ${client_port}:8069
  links:
    - db
  volumes:
    - odoo_webdata:/var/lib/odoo
    - odoo_config:/etc/odoo
    - odoo_addons:/mnt/extra-addons

db:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=${db_user}
    - POSTGRES_PASSWORD=${db_password}
  volumes:
    - odoo_db:/var/lib/postgresql/data
