  lb:
   ports:
   - 80:80
   image: rancher/load-balancer-service
   external_links:
   - etherpad/etherpad:etherpad
   - wordpress/wordpress:wordpress
   - rocket-chat/rocketchat:rocketchat
   - seafile/seafile:seafile
#   - {$stack_5}/{$service_5}:{$service_5}
   labels:
    # Put load balancer containers only on hosts without label availability=temporal
     io.rancher.scheduler.affinity:host_label_ne: availability=temporal
    # Requests to http://app.example.com/foo:80 should be routed to web1 over port 8000
     io.rancher.loadbalancer.target.etherpad/etherpad: etherpad.educaas.io:80=9001
     io.rancher.loadbalancer.target.wordpress/wordpress: wordpress.educaas.io:80=8080
     io.rancher.loadbalancer.target.rocket-chat/rocketchat: rocketchat.educaas.io:80=3000
     io.rancher.loadbalancer.target.seafile/seafile: seafile.educaas.io:80=8000
#     io.rancher.loadbalancer.target.{$stack_5}/{$service_5}: {$subdomain_5}.{$hostname}:80={$port_5}
