name: Jupyter Base Notebook
description: |
  The Jupyter Notebook is a web application that allows you to create and share documents that contain live code, equations, visualizations and explanatory text..
version: v0.1-educaas
category: Escribir
