.catalog:
  name: "GlusterFS"
  version: v0.1-educaas
  description: "Gluster FS (3x) replicated volume"
  minimum_rancher_version: v1.0.0-rc2
  questions:
    - variable: "VOLUME_NAME"
      description: "Name to give the Gluster volume"
      label: "Volume Name"
      required: true
      default: "my_vol"
      type: "string"
