app:
  image: nextcloud:fpm
  links:
    - db
  volumes:
    - nextcloud_data:/usr/src/nextcloud/data
    - nextcloud_config:/usr/src/nextcloud/config
    - nextcloud_apps:/usr/src/nextcloud/apps
    - nextcloud_customapps:/usr/src/nextcloud/custom_apps
    - nextcloud_themes:/usr/src/nextcloud/themes
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=${db_password}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${db_password}
  volumes:
    - nextcloud_db:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

nginx:
    image: dalareo/nextcloud-nginx
    links:
      - collabora
      - app
    environment:
      - VIRTUAL_HOST=${domain}
    labels:
      io.rancher.scheduler.affinity:host_label: availability=permanent

collabora:
  image: collabora/code
  environment:
    - domain=${escaped_domain}
    - username=${username_office}
    - password=${password_office}
  cap_add:
    - MKNOD
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent
