nextcloud:
  image: wonderfall/nextcloud
  ports:
    - ${client_port}:8888
  links:
    - nextcloud-db:nextcloud-db
  volumes:
    - nextcloud_data:/data
    - nextcloud_config:/config
    - nextcloud_apps:/apps2
    - nextcloud_themes:/nextcloud/themes
  environment:
#    - UID=1000
#    - GID=1000
#    - UPLOAD_MAX_SIZE=10G
#    - APC_SHM_SIZE=128M
#    - OPCACHE_MEM_SIZE=128
#    - CRON_PERIOD=15m
#    - TZ=Europe/Berlin
    - DOMAIN=${cloud_domain}
    - DB_TYPE=mysql
    - DB_NAME=nextcloud
    - DB_USER=nextcloud
    - DB_PASSWORD=${db_password}
    - DB_HOST=nextcloud-db
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

nextcloud-db:
  image: mariadb:10
  environment:
    - MYSQL_ROOT_PASSWORD=${db_password}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${db_password}
  volumes:
    - nextcloud_db:/var/lib/mysql
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent

proxy:
    image: nginx
    links:
      - code
    environment:
      - VIRTUAL_HOST=${domain}
    labels:
      io.rancher.scheduler.affinity:host_label: availability=permanent

code:
  image: collabora/code
  ports:
    - 9980:9980
  environment:
    - domain=${escaped_domain}
    - username=${username_office}
    - password=${password_office}
  cap_add:
    - MKNOD
  labels:
    io.rancher.scheduler.affinity:host_label: availability=permanent
